### PR TITLE
build: support correct linker flags on macOS

### PR DESCRIPTION
**Pull request by alebcay**
In macOS, shared objects use the `.dylib` extension (DYnamic LIBrary) and are versioned as `libfoo.<version>.dylib`.

Set SHARED and SONAME variables appropriately if building on macOS, and adjust the SONAME and clean targets accordingly as well.

---

I figure this is probably a mirror of the repository at git.1wt.eu. Unfortunately I don't have `git-send-email` set up; if it's more convenient, you can also just [download this patch (plain text) on its own](https://github.com/wtarreau/libslz/files/7026071/0001-build-support-correct-linker-flags-on-macOS.patch.txt) (`.txt` file extension appended to allow GitHub to attach it).

### CODE REVIEW

**Comment by TimWolla** [comment]
> if it's more convenient, you can also just [download this patch (plain text) on its own](https://github.com/wtarreau/libslz/files/7026071/0001-build-support-correct-linker-flags-on-macOS.patch.txt) (`.txt` file extension appended to allow GitHub to attach it).

@alebcay FWIW: One can also simply append `.patch` to a PR URL to obtain a patch file: https://github.com/wtarreau/libslz/pull/1.patch

I'll also ping Willy by email, because I assume that he missed this PR.

**Comment by wtarreau** [comment]
Thanks @alebcay for the patch and @TimWolla for the ping. I indeed almost never receive notifications or they get lost in the noise.

@alebcay I'd like you to proceed differently to determine the platform. Using `uname` is not the correct approach because it causes trouble in cross-compiled environments since it checks the build host and not the target host. The correct method is to check what OS the toolchain is made for. The simplest way to do that is by checking the output of `$(CC) -dumpmachine`. For example on my machine it does this:
```
$ clang -dumpmachine
x86_64-unknown-linux-gnu
$ gcc -dumpmachine
x86_64-slackware-linux
```
Sometimes the vendor is missing (e.g. on ubuntu here):
```
$ gcc -dumpmachine
x86_64-linux-gnu
```

However you can rely on the last part ("gnu" is often appended after "linux" but not always),
so `$(CC) -dumpmachine | sed -e 's,-gnu[^-]*,,; s,.*-,,'` should always return the OS name. If you use that in your PLATFORM variable instead of `uname -s` you can then rely on the BFD target name and that will automatically adjust to the compiler's target.

Please check on your platform, as I'm not sure what macOS returns there, but I'm obviously fine with merging your patch once we know what to check for (most likely `darwin` in lowercase).

**Comment by alebcay** [comment]
Thanks, cross-compilation is something I hadn't considered. I've tried two different toolchains installed on my machine (Apple's provided compiler, and one shipped via a package manager):
```
❯ gcc -dumpmachine
x86_64-apple-darwin20.6.0

❯ gcc-11 -dumpmachine
x86_64-apple-darwin20
```

So I would reckon that we can match on `darwin*` (some older versions of macOS have older versions of Darwin kernel but use the same linker flags, so some generality is good). So the `sed` filter probably needs a bit of adjusting.

I do wonder how this would behave on PureDarwin, not sure how their compiler/linker works but considering how little PureDarwin is used, I guess it's safe enough to assume that `darwin` == macOS.

**Comment by wtarreau** [comment]
OK then I think we could adjust around this:
```
PLATFORM := $(shell $(CC) -dumpmachine | sed -e 's,-gnu[^-]*,,; s,.*-,,')
...
ifneq $(filter %darwin%, $(PLATFORM))
    ... # darwin-specific stuff
else
   ...  # other
fi
```

**Comment by alebcay** [comment]
Thanks, I've rebased this branch your suggested changes, with a few additional changes for syntax.

**Comment by wtarreau** [comment]
Perfect, it looked good and still works on linux, so I've applied it now.
Thank you!

**Comment by alebcay** [comment]
Thanks for reviewing! Closed via 5c5486ea11917da9b1ee2ac65e988bcf9532a5e9.

**Pull request closed without merging**
